apiVersion: v1
kind: Namespace
metadata:
  name: mar
  labels:
    environment-id: env_61986333-f64f-4eb4-a0a8-0943c39da76f
    project-id: project_95424b57-1296-424f-9777-fb243805d37c
    project-name: dogHouse7
    environment-name: staging
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
